### ISSUE TITLE
State machine gem

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pul-store#192]
This is exactly what I was looking for when I started the LAE models: 

https://github.com/pluginaweek/state_machine 

Explore it a little more and consider refactoring. Test coverage for the states we have is very good, so hopefully it won't be too difficult. It may not be maintained anymore, in which case check out:

https://github.com/aasm/aasm

as well.

**Comment by kevinreiss** [comment]
@jpstroop roads not taken?
