### ISSUE TITLE
Object Assigned to Two Models?

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul-store#347]
While testing some permissions updates in the demo system I managed to save a folder http://pulstoredemo.princeton.edu/lae/folders/puls:074j3 as a box http://pulstoredemo.princeton.edu/lae/boxes/puls:074j3. What do you think the cleanest way to undo saving an object that was cast as the wrong type might be @jpstroop.

**Comment by kevinreiss** [comment]
@jpstroop Is it worth writing something that explicitly errors out if an edit form is ever loaded with an object type that doesn't match what you think you are editing?

**Comment by jpstroop** [comment]
Could, I suppose; do you think we really need it? How is this likely to happen?

**Comment by kevinreiss** [comment]
It only happened to me when I was manually copied and pasting IDs into browser. Probably not too likely.
