### ISSUE TITLE
Need a field for collation keys

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pul-store#66]
I.E. for filtering subsets of the repository. They should be short, like 'lae' or 'wa', and probably be part of Project and Collection Models, but added to a separate , repeatable attribute in a callback on save.

This should probably be added to PulStore::Base

**Comment by kevinreiss** [comment]
@jpstroop roads not taken?

**Comment by jpstroop** [comment]
I think so. The FCDM has an approach to this that I think will work.
